import { useSession, signIn, signOut } from "next-auth/react";
import { Container, Heading, Text } from "@chakra-ui/react";
import Head from "next/head";
import MenuBar from "@/components/menuBar";

export default function Home() {
  const { data: session } = useSession();

  if (session) {
    return (
      <>
        Signed in as {session.user.email} <br />
        <button onClick={() => signOut()}>Sign out</button>
      </>
    );
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MenuBar />
      <Container p="20px" centerContent="true">
        <Heading size="3xl">Homepage</Heading>
        <Text mt="3.5" bg="purple.500" color="white" p="10px 20px">
          Welcome to favorite cities website! <br />
          Not signed in <br />
          <button onClick={() => signIn()}>Sign in</button>
        </Text>
      </Container>
    </>
  );
}
